# Generated by Django 4.2.3 on 2023-09-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_carmake_country_alter_carmodel_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='fuel',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='kilometer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='location',
            field=models.CharField(default='thrissur', max_length=100),
        ),
    ]
