# Generated by Django 4.2.3 on 2023-09-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_carmodel_fuel_carmodel_kilometer_carmodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(default='', max_length=100),
        ),
    ]
